/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Addr, InstantiateMsg, ExecuteMsg, CallbackData, Binary, CallbackMsg, QueryMsg, Config, Decimal, StateResponse } from "./BowCompat.types";
import { CamelCasedProperties } from "type-fest";
export abstract class BowCompatExecuteMsgBuilder {
  static updateConfig = ({
    bow,
    hub,
    liquifier,
    owner
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_config: unknown;
  }>["update_config"]>): ExecuteMsg => {
    return {
      update_config: ({
        bow,
        hub,
        liquifier,
        owner
      } as const)
    };
  };
  static callback = ({
    callback,
    data
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    callback: unknown;
  }>["callback"]>): ExecuteMsg => {
    return {
      callback: ({
        callback,
        data
      } as const)
    };
  };
  static bond = (): ExecuteMsg => {
    return {
      bond: ({} as const)
    };
  };
  static queueUnbond = (): ExecuteMsg => {
    return {
      queue_unbond: ({} as const)
    };
  };
  static withdrawUnbonded = (): ExecuteMsg => {
    return {
      withdraw_unbonded: ({} as const)
    };
  };
}
export abstract class BowCompatQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static state = (): QueryMsg => {
    return {
      state: ({} as const)
    };
  };
}