/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  bow: Addr;
  hub: Addr;
  liquifier: Addr;
  owner: Addr;
}
export type ExecuteMsg = {
  update_config: {
    bow?: Addr | null;
    hub?: Addr | null;
    liquifier?: Addr | null;
    owner?: Addr | null;
  };
} | {
  callback: CallbackMsg;
} | {
  bond: {};
} | {
  queue_unbond: {};
} | {
  withdraw_unbonded: {};
};
export type CallbackData = string;
export type Binary = string;
export interface CallbackMsg {
  callback: CallbackData;
  data: Binary;
}
export type QueryMsg = {
  config: {};
} | {
  state: {};
};
export interface Config {
  bow: Addr;
  hub: Addr;
  liquifier: Addr;
  owner: Addr;
}
export type Decimal = string;
export interface StateResponse {
  exchange_rate: Decimal;
}