/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Liquifier.types";
import * as _1 from "./Liquifier.msg-builder";
import * as _2 from "./BowCompat.types";
import * as _3 from "./BowCompat.msg-builder";
import * as _4 from "./Unifier.types";
import * as _5 from "./Unifier.msg-builder";
import * as _6 from "./Hub.types";
import * as _7 from "./Hub.msg-builder";
export namespace contracts {
  export const Liquifier = { ..._0,
    ..._1
  };
  export const BowCompat = { ..._2,
    ..._3
  };
  export const Unifier = { ..._4,
    ..._5
  };
  export const Hub = { ..._6,
    ..._7
  };
}