/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.34.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  hub_contract: Addr;
  owner: Addr;
  unifier_contract: Addr;
}
export type ExecuteMsg = {
  wrap: WrapMsg;
} | {
  unwrap: UnwrapMsg;
} | {
  update_config: ConfigUpdate;
};
export type CallbackData = string;
export type CallbackData1 = string;
export type UnwrapTarget = "hub" | "underlying";
export interface WrapMsg {
  callback?: CallbackData | null;
}
export interface UnwrapMsg {
  callback?: CallbackData1 | null;
  target?: UnwrapTarget | null;
}
export interface ConfigUpdate {
  owner?: Addr | null;
}
export type QueryMsg = {
  config: {};
} | {
  state: {};
};
export type Denom = string;
export interface ConfigResponse {
  hub_contract: Addr;
  hub_denom: Denom;
  owner: Addr;
  receipt_denom: Denom;
  underlying_denom: Denom;
  unifier_contract: Addr;
}
export type Decimal = string;
export type Uint128 = string;
export interface StateResponse {
  rate: Decimal;
  supply: Uint128;
}